baseurl = "/"
languageCode = "en-uk"
title = "Timothy Hyndman"
theme = "AllinOne"
preserveTaxonomyNames = true
Paginate = 3
# disqusShortname = ""
googleAnalytics = "G-50CMXZPL44"
pluralizeListTitles = false

# Set the followings to true as part of your site SEO
enableRobotsTXT = true
canonifyurls = true

builddrafts                = false
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = false
summaryLength              = 30

pygmentsuseclasses         = true


[permalinks]
#  blog                     = "blog/:slug/"
  
[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"

[menu]
  [[menu.main]]
    name                   = "CV"
    weight                 = -120
    identifier             = "cv"
    url                    = "CV.pdf"  

[params]
  faviconfile              = "img/icon.jpg"               # from static/
  avatar                   = "img/icon.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Timothy Hyndman"
  description              = []           # appears in the site header when set to a non-empty string
  welcome_head             = ""
  welcome_word             = ""

  latestpostscount         = 3                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = true                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "timothyhyndman@gmail.com"
  github                   = "//github.com/timothyhyndman"
#  linkedin                 = "//linkedin.com/in/timothyhyndman"
  # facebook                 = "//facebook.com/you"
  # googleplus               = "//google.com/you"
  # twitter                  = "//twitter.com/you"
  # px500                    = "//px500"
  # instagram                = "//instagram.com/you"
  include_rss              = false                          # include RSS <link> tag in <head> and show RSS icon
